#!/bin/sh
# Static "build" — there is no bundler here, and that is the point: the site is
# hand-written HTML/CSS/JS with zero dependencies, so the only build step is
# stamping the backend URL into config.js.
#
# API_URL must be the backend's PUBLIC url. On Render, do NOT wire it from the
# service's `host` property: that resolves to the INTERNAL service name, which
# only the private network can reach, and the deck loads straight to "backend
# unreachable". Copy the URL shown on the backend's service page.
set -eu
API="${API_URL:-}"

# A BUILD STAMP, so "is the new version actually live?" is answerable in one
# glance instead of by guessing. Asset names here are stable and unhashed, so
# a stale CDN or browser cache looks EXACTLY like a successful deploy of
# unchanged code — clean logs, green deploy, identical page. This is the thing
# that tells those two apart.
STAMP="${RENDER_GIT_COMMIT:-local}"
STAMP="$(printf '%s' "$STAMP" | cut -c1-7)"
BUILT="$(date -u '+%Y-%m-%d %H:%M UTC')"

cat > config.js <<EOF
/* generated by build.sh — do not edit; set API_URL in the environment */
window.GG_API = "${API}";
window.GG_BUILD = { commit: "${STAMP}", built: "${BUILT}" };
EOF
echo "config.js -> GG_API=\"${API}\"  build=${STAMP} (${BUILT})"
